url: "https://previsionweb.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Prévision Web - Code, No-code, Pseudo-code & Automatisations " # the name of your site, e.g. ACME Corp.
author: "ML - Mathieu Lagüe - Développeur Web"
timezone: Europe/Paris
lang: fr
locale: fr_FR

# build settings
markdown: kramdown
kramdown:
  #hard_wrap: false
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
highlighter: rouge
tailwindcss:
  css_path: "./_tailwind.css"



plugins:
  - jekyll-tailwindcss

exclude:
 # - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - README.md
  - bin
